type = "awards"
title = "Awards"

[[items]]
title = "Outstanding Paper Award & Oral"
organization = "FMEA Workshop, CVPR 2026"
date = "2026"

[[items]]
title = "Best Paper Runner-up Award"
organization = "3D LLM-VLA Workshop, CVPR 2026"
date = "2026"

[[items]]
title = "Best Paper Runner-up Award"
organization = "Rational Robots Workshop, CoRL 2025"
date = "2025"

[[items]]
title = "Best Paper Nominee"
organization = "Data Workshop, CoRL 2025"
date = "2025"

