type = "experience"
title = "Experience"

[[items]]
organization = "Allen Institute for Artificial Intelligence"
group = "Perceptual Reasoning and Interaction Research (PRIOR)"
logo = "/logos/ai2.png"
advisor = "Advised by Prof. Ranjay Krishna and Prof. Jiafei Duan"

[[items.roles]]
title = "Student Researcher"
date = "Nov. 2025 - March. 2026"

[[items.roles]]
title = "Student Collaborator"
date = "Apr. 2025 - Oct. 2025"

